# Update an MPR package.
name: update-pkg
on:
  pull_request:

jobs:
  get-distro-image-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: set up makedeb and Prebuilt-MPR APT repositories
        uses: makedeb/setup-makedeb@main
        with:
          makedeb-repo: false
          pbmpr-repo: true
      - name: update APT cache
        run: sudo apt update
      - name: install prerequisites
        run: sudo apt install dasel jq -y
      - name: get package base
        id: pkgbase
        run: echo "pkgbase=${GITHUB_HEAD_REF}" | sed 's|pkg-update/||' >> "${GITHUB_OUTPUT}"
      - name: Convert Comma-Separated Distro String into Distro Array
        id: set-matrix
        run: |
          allowed_distros=()
          blocked_distros=($(dasel -f packages.toml -w json | jq -r '."${{ steps.pkgbase.outputs.pkgbase }}".blocked_distros[]'))

          for distro in 'focal' 'jammy' 'bullseye'; do
            if ! printf '%s\n' "${blocked_distros[@]}" | grep -Fq "${distro}"; then

              if [[ "${distro}" == 'bullseye' ]]; then
                allowed_distros+=("debian-${distro}")
              else
                allowed_distros+=("ubuntu-${distro}")
              fi
            fi
          done

          printf '%s\n' "${allowed_distros[@]}" | sed 's|.*|"&", |' | tr -d '\n' | sed 's|, $||' | sed 's|.*|matrix=[&]|' > "${GITHUB_OUTPUT}"
  update-pkg:
    runs-on: ubuntu-latest
    needs: get-distro-image-matrix
    container:
      image: proget.hunterwittenborn.com/docker/makedeb/makedeb:${{ matrix.distro-image }}
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        distro-image: ${{ fromJson(needs.get-distro-image-matrix.outputs.matrix) }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: set up makedeb and Prebuilt-MPR APT repositories
        uses: makedeb/setup-makedeb@main
        with:
          pbmpr-repo: true
      - name: correct permissions so makedeb can run
        run: chown 'makedeb:makedeb' pkg/ -R
      - name: run makedeb
        run: cd pkg/ && sudo -u makedeb makedeb -si --no-confirm
      - name: upload build artifacts
        uses: actions/checkout@v3
        with:
          name: ${{ matrix.distro_image }}
          path: '*.deb'
